apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: humourmind/invoice
      context: ./invoice
      jib: {}
    - image: humourmind/notification
      context: ./notification
      jib: {}
    - image: humourmind/product
      context: ./product
      jib: {}
    - image: humourmind/store
      context: ./store
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
